### PR TITLE
Switched to CMake, moved some code to separate libs

### PR DESCRIPTION
**Pull request by Randl**
I'm not CMake expert, but I believe it should work. Still not builds on gcc/mingw because of inline asm.

Also moved miracl, skype, sqlite to separate folder instead of own copy in each folder.

### CODE REVIEW

**Comment by skypeopensource** [comment]
You want to merge with main branch?
Its Visual Studio 2010 projects.
Maybe create for or separate repo for you cmake changes?
Then instruct me how to do this, i am a bit new in github. and git.

**Comment by Randl** [comment]
@skypeopensource CMake supports VS projects too

**Comment by Randl** [comment]
@skypeopensource You can read more about how to use CMake with VS [here](https://cognitivewaves.wordpress.com/cmake-and-visual-studio/). Also, this partially resolves #1

**Comment by skypeopensource** [comment]
Can i ask you to send pull request to this repo: skypeopensource2_dev
Which i create specially for modification purposes from community.

**Comment by Randl** [comment]
@skypeopensource I believe it's better to create separate [branch](https://help.github.com/articles/creating-and-deleting-branches-within-your-repository/) instead of separate repo

**Comment by skypeopensource** [comment]
Thank you, but no.

**Comment by Randl** [comment]
@skypeopensource But why? That's exact a point of branches - different versions and modifications for same project, while different repos are usually used for different projects.

**Comment by Randl** [comment]
I've got the code compiling on MinGW except couple of minor issues, namely #8 and inline asm which should be rewritten for gcc.

**Comment by skypeopensource** [comment]
@Randl 

https://github.com/skypeopensource/tool_linuxbuild/tree/master/skysearch2_linux
You have take a look on this?

**Comment by Randl** [comment]
@skypeopensource not yet, but I see there is some code which may be useful.

I hope I'll have time to test it on both MinGW and VS tomorrow to make sure nothing is broken. Meanwhile I try to do as few changes as possible to not broke code I don't really understand. 

Can you elaborate, which flags do you use to build Debug/Release version please?

**Comment by skypeopensource** [comment]
@Randl 

Minimum, defaults should be ok.

**Comment by Randl** [comment]
@skypeopensource Can you please confirm that my current CMake version compiles and works on your side? If no, what are the problems?

Also, if you insist on merging all community changes to different repo, can you create a [CONTRIBUTING](https://github.com/blog/1184-contributing-guidelines) file and mention it there?

**Comment by Randl** [comment]
@skypeopensource ???

Also, please check places marked with `FIXME`, like [here](https://github.com/Randl/skypeopensource2/blob/master/skype/skype_rc4.c#L293), [here](https://github.com/Randl/skypeopensource2/blob/master/skype/pack-4142.c#L892) or [here](https://github.com/Randl/skypeopensource2/blob/master/goodsendrelay/tcp_sess1.c#L196). These are possible bugs I managed to find while working on code.

**Comment by skypeopensource** [comment]
@Randl 

Thank you. I will do CONTRIBUTING file.

Also, you can check wiki of the project:
https://github.com/skypeopensource/skypeopensource2/wiki

I add one article about connect. May be it will useful somehow for you.

**Comment by Randl** [comment]
@skypeopensource Have you tried to build and run my version? I'd want to be sure I haven't broken anything while migrating to CMake. As for now it builds both on VS and MinGW, but I want to ensure it works before I continue the work.

**Comment by Randl** [comment]
@skypeopensource Please can you run my code and confirm it's working? I want to get it working on Linux, but I can proceed until you (or someone else?) test it and all current bugs are fixed. 

Is something preventing you prom run it? Can you at least give any anwser?

**Comment by skypeopensource** [comment]
@Randl 
Sorry for delay. 

I dont work with CMake before. Can you give me brief description of it?
I need mingw to test it?
Or something else?

**Comment by Randl** [comment]
@skypeopensource No you can use CMake with Visual Studio. Check this link https://cognitivewaves.wordpress.com/cmake-and-visual-studio/
You need only CMake which will create you VS project, then just open it and work as regular.

**Comment by Randl** [comment]
@skypeopensource ...

**Comment by skypeopensource** [comment]
@Randl 
I install CMake.

**Comment by skypeopensource** [comment]
I cant see any advantages of using it. Sorry.
For windows we have VS10, for linux - automake.

If you want, you can do CMakeList.txt for each directory and pull it in _dev repo. Its ok.

But not move any files. Even if same files with same name are equal. Some, not. For example ext42.c.

**Comment by skypeopensource** [comment]
I mean this is:

sqlite moved to separate folder			
crypto moved to separate folder			
miracl moved to separate folder			
skype moved to separate folder

Wrong. Dont to this.

**Comment by AntonBoch1244** [comment]
@skypeopensource, I ask that question at once.
You know how to make cross-platform project?
I view don't, change my mind if you wanted help from community.
Randl know more by compare to you.

**Comment by AntonBoch1244** [comment]
From: Evgeny Zheltonozhskiy <zheltonozhskiy@gmail.com>

Why would you put same files twice in different places? https://en.m.wikipedia.org/wiki/Don%27t_repeat_yourself

I mean, that's basic principle of programming. Especially if we're talking about 3rd party line like miracl or sqlite. Anyway, why would you want it? You have different implementations of same functions for different parts of project? That's counter-intuitive, different functions should have different names, give them different names then. 

Advantages? As for now, the project can be built only with VS10 (automake project is not present). Even the small part of people in FOSS community who use Windows usually use MinGW resulting in really tiny amount of people can actually build you project without installing new compiler/OS. My fork builds on MinGW now and should build on gcc in Linux too (will check it next week).

I might repeat what I already said, but while reverse engineering part of the project is really great, the infrastructure decisions are weird and unreasonable. The folder structure is messy, binary files are in code tree, etc, and we haven't seen any reasoning about it. I was pretty enthusiastic about this project and contribution to it, but your decisions make it too hard if not impossible to contribute (at least for me, but based on amount of PRs, not only) so that's it. As for now, I'll stick with my fork and hopefully make it run on Linux, leaving it there. You re welcome to merge it anytime. Maybe someone else will persuade you to use better practices for code structure, version control, etc.

**Comment by skypeopensource** [comment]
I already told anything what i want. No more discussions on this.

**Comment by jonjomckay** [comment]
For what it's worth @skypeopensource, I think you're making the wrong choice here - this could have been a huge community project with a noble goal, but your bizarre  and non-sensical decisions on things like repositories (use branches, not separate repos!), code structure (use a standard way so more people can contribute), build system (just merge the CMake pull request already, so people can build the project on essentially any free operating system, with a free compiler!) and your cold responses to contributions aren't helping anything. Developers will not contribute to an insane project with indecipherable rules - trust me. 

If I were @Randl, I would make his fork the "canonical" source for this project as this one seems to be going nowhere. Which is a great shame.

**Comment by skypeopensource** [comment]
No more discussion on this. Its MY decisions, not yours OKAY? Do your own reversing and setup your own rules. 

My rules for contribution on this project will be announce in near future. Please, wait.

**Pull request closed without merging**
